version: "3"
services:

  db:
    build:
      context: ./docker/db
    ports:
      - "3306:3306"

  app:
    build:
      context: ./docker/app
    ports:
      - "8080:80"
    volumes:
      - .:/opt/project
